# Generated by Django 5.2.5 on 2025-11-20 15:43

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0210_macaddress_ordering'),
        ('extras', '0129_fix_script_paths'),
        ('tenancy', '0020_remove_contactgroupmembership'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('device', models.ManyToManyField(blank=True, related_name='maintenance_actions', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machine', models.ManyToManyField(blank=True, related_name='maintenance_actions', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'Maintenance Action',
                'verbose_name_plural': 'Maintenance Actions',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MaintenancePlannedActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('grouping_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('device', models.ManyToManyField(blank=True, related_name='plans_device', to='dcim.device')),
                ('maintenance_action', models.ManyToManyField(related_name='plans_maintenance_actions', to='adestis_netbox_maintenance_management.maintenanceactions')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_tenant', to='tenancy.tenant')),
                ('virtual_machine', models.ManyToManyField(blank=True, related_name='plans_vm', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'Maintenance Planned Action',
                'verbose_name_plural': 'Maintenance Planned Actions',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_planned_actions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_planned_actions', to='adestis_netbox_maintenance_management.maintenanceplannedactions')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Maintenance Report',
                'verbose_name_plural': 'Maintenance Reports',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MaintenanceTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('device', models.ManyToManyField(blank=True, related_name='tasks_device', to='dcim.device')),
                ('maintenance_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_maintenance_actions', to='adestis_netbox_maintenance_management.maintenanceactions')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machine', models.ManyToManyField(blank=True, related_name='tasks_vm', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'Maintenance Tasks',
                'verbose_name_plural': 'Maintenance Tasks',
                'ordering': ('name', 'maintenance_windows__start_time'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='maintenanceplannedactions',
            name='maintenance_tasks',
            field=models.ManyToManyField(blank=True, related_name='plans_tasks', to='adestis_netbox_maintenance_management.maintenancetasks'),
        ),
        migrations.AddField(
            model_name='maintenanceplannedactions',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='plans', to='adestis_netbox_maintenance_management.maintenancetasks'),
        ),
        migrations.CreateModel(
            name='MaintenanceWindows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('week_in_month', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('schedule_type', models.CharField(default='select', max_length=20)),
                ('start_day', models.DateField(blank=True, null=True)),
                ('end_day', models.DateField(blank=True, null=True)),
                ('recurrence_type', models.CharField(blank=True, default='select', max_length=20, null=True)),
                ('weekdays', models.CharField(blank=True, max_length=50, null=True)),
                ('monthdays', models.DateField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('special_ordinal', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machine', models.ManyToManyField(blank=True, related_name='maintenance_window', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'Maintenance Window',
                'verbose_name_plural': 'Maintenance Windows',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='maintenancetasks',
            name='maintenance_windows',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_maintenance_windows', to='adestis_netbox_maintenance_management.maintenancewindows'),
        ),
        migrations.AddField(
            model_name='maintenanceplannedactions',
            name='maintenance_windows',
            field=models.ManyToManyField(related_name='plans_maintenance_windows', to='adestis_netbox_maintenance_management.maintenancewindows'),
        ),
        migrations.AddField(
            model_name='maintenanceactions',
            name='maintenance_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_windows', to='adestis_netbox_maintenance_management.maintenancewindows'),
        ),
    ]
