# Generated by Django 5.1.8 on 2026-05-28 12:06

import django.core.validators
import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0123_journalentry_kind_default'),
        ('tenancy', '0017_natural_ordering'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('device', models.ManyToManyField(blank=True, related_name='maintenance_actions', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_tenant', to='tenancy.tenant')),
                ('virtual_machine', models.ManyToManyField(blank=True, related_name='maintenance_actions', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'Maintenance Action',
                'verbose_name_plural': 'Maintenance Actions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('week_in_month', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('schedule_type', models.CharField(default='select', max_length=20)),
                ('start_day', models.DateField(blank=True, null=True)),
                ('end_day', models.DateField(blank=True, null=True)),
                ('recurrence_type', models.CharField(blank=True, default='select', max_length=20, null=True)),
                ('weekdays', models.CharField(blank=True, max_length=50, null=True)),
                ('monthdays', models.DateField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('special_ordinal', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machine', models.ManyToManyField(blank=True, related_name='maintenance_window', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'Maintenance Window',
                'verbose_name_plural': 'Maintenance Windows',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('device', models.ManyToManyField(blank=True, related_name='tasks_device', to='dcim.device')),
                ('maintenance_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_maintenance_actions', to='adestis_netbox_maintenance_management.maintenanceactions')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ManyToManyField(blank=True, related_name='tasks_tenant', to='tenancy.tenant')),
                ('virtual_machine', models.ManyToManyField(blank=True, related_name='tasks_vm', to='virtualization.virtualmachine')),
                ('maintenance_windows', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_maintenance_windows', to='adestis_netbox_maintenance_management.maintenancewindows')),
            ],
            options={
                'verbose_name': 'Maintenance Task',
                'verbose_name_plural': 'Maintenance Tasks',
                'ordering': ('name', 'maintenance_windows__start_time'),
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=150)),
                ('reference_number', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('version', models.CharField(blank=True, null=True)),
                ('device', models.ManyToManyField(blank=True, related_name='device_plans', to='dcim.device')),
                ('maintenance_action', models.ManyToManyField(related_name='maintenance_action_plans', to='adestis_netbox_maintenance_management.maintenanceactions')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans_tenant', to='tenancy.tenant')),
                ('virtual_machine', models.ManyToManyField(blank=True, related_name='vm_plans', to='virtualization.virtualmachine')),
                ('maintenance_windows', models.ManyToManyField(related_name='maintenance_windows_plans', to='adestis_netbox_maintenance_management.maintenancewindows')),
            ],
            options={
                'verbose_name': 'Maintenance Plan',
                'verbose_name_plural': 'Maintenance Plans',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlannedActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('grouping_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('device', models.ManyToManyField(blank=True, related_name='plans_device', to='dcim.device')),
                ('maintenance_action', models.ManyToManyField(related_name='plans_maintenance_actions', to='adestis_netbox_maintenance_management.maintenanceactions')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_tenant', to='tenancy.tenant')),
                ('virtual_machine', models.ManyToManyField(blank=True, related_name='plans_vm', to='virtualization.virtualmachine')),
                ('maintenance_tasks', models.ManyToManyField(blank=True, related_name='plans_tasks', to='adestis_netbox_maintenance_management.maintenancetasks')),
                ('tasks', models.ManyToManyField(blank=True, related_name='plans', to='adestis_netbox_maintenance_management.maintenancetasks')),
                ('maintenance_windows', models.ManyToManyField(related_name='plans_maintenance_windows', to='adestis_netbox_maintenance_management.maintenancewindows')),
            ],
            options={
                'verbose_name': 'Planned Action',
                'verbose_name_plural': 'Planned Actions',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='maintenanceactions',
            name='maintenance_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_windows', to='adestis_netbox_maintenance_management.maintenancewindows'),
        ),
    ]
