# Generated by Django 5.2.5 on 2025-10-07 12:53

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0210_macaddress_ordering'),
        ('extras', '0129_fix_script_paths'),
        ('tenancy', '0020_remove_contactgroupmembership'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('device', models.ManyToManyField(blank=True, related_name='maintenance_actions', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machine', models.ManyToManyField(blank=True, related_name='maintenance_actions', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'Maintenance Action',
                'verbose_name_plural': 'Maintenance Actions',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MaintenancePlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('maintenance_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adestis_netbox_maintenance_management.maintenanceactions')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_tenant', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Maintenance Plans',
                'verbose_name_plural': 'Maintenance Plans',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_plans', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='adestis_netbox_maintenance_management.maintenanceplans')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Maintenance Report',
                'verbose_name_plural': 'Maintenance Reports',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MaintenanceWindows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('schedule_type', models.CharField(default='select', max_length=20)),
                ('start_day', models.DateField(blank=True, null=True)),
                ('end_day', models.DateField(blank=True, null=True)),
                ('recurrence_type', models.CharField(blank=True, max_length=20, null=True)),
                ('weekdays', models.CharField(blank=True, max_length=50, null=True)),
                ('monthdays', models.DateField(blank=True, null=True)),
                ('special_ordinal', models.CharField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machine', models.ManyToManyField(blank=True, related_name='maintenance_window', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'Maintenance Window',
                'verbose_name_plural': 'Maintenance Windows',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='maintenanceactions',
            name='maintenance_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_windows', to='adestis_netbox_maintenance_management.maintenancewindows'),
        ),
    ]
