# Generated by Django 5.2.5 on 2025-10-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancewindows',
            name='clock',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
