# Generated by Django 5.2.5 on 2025-11-21 08:21

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0001_initial'),
        ('extras', '0129_fix_script_paths'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=150)),
                ('refrence_number', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans_tenant', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Maintenance Plan',
                'verbose_name_plural': 'Maintenance Plans',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
