# Generated by Django 5.2.5 on 2025-10-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancewindows',
            name='special_weekday',
        ),
    ]
