# Generated by Django 5.2.5 on 2025-10-07 13:40

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0001_initial'),
        ('extras', '0129_fix_script_paths'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('maintenance_action', models.ManyToManyField(related_name='tasks_maintenance_actions', to='adestis_netbox_maintenance_management.maintenanceactions')),
                ('maintenance_windows', models.ManyToManyField(related_name='tasks_maintenance_windows', to='adestis_netbox_maintenance_management.maintenancewindows')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machine', models.ManyToManyField(blank=True, related_name='tasks_vm', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'Maintenance Tasks',
                'verbose_name_plural': 'Maintenance Tasks',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
