# Generated by Django 5.1.8 on 2025-09-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceactions',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='maintenanceplans',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='maintenancereport',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='maintenancewindows',
            options={'ordering': ('name',)},
        ),
    ]
