# Generated by Django 5.1.8 on 2025-09-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancewindows',
            name='weekdays',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
