# Generated by Django 5.1.8 on 2026-06-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0001_initial'),
        ('tenancy', '0017_natural_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetasks',
            name='tenant',
        ),
        migrations.AddField(
            model_name='maintenancetasks',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_tenant', to='tenancy.tenant'),
        ),
    ]
