# Generated by Django 5.2.5 on 2025-10-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0002_maintenancewindows_clock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancewindows',
            old_name='clock',
            new_name='time',
        ),
    ]
