# Generated by Django 5.2.5 on 2025-09-24 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0002_alter_maintenanceactions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceplans',
            name='maintenance_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_action', to='adestis_netbox_maintenance_management.maintenanceactions'),
        ),
    ]
