# Generated by Django 5.2.5 on 2025-10-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0002_maintenancetasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetasks',
            name='maintenance_action',
        ),
        migrations.RemoveField(
            model_name='maintenancetasks',
            name='maintenance_windows',
        ),
        migrations.AddField(
            model_name='maintenancetasks',
            name='maintenance_action',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='task_maintenance_windows', to='adestis_netbox_maintenance_management.maintenanceactions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancetasks',
            name='maintenance_windows',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='task_maintenance_windows', to='adestis_netbox_maintenance_management.maintenancewindows'),
            preserve_default=False,
        ),
    ]
