# Generated by Django 5.2.5 on 2025-11-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0002_remove_maintenancewindows_special_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancewindows',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
