# Generated by Django 5.1.8 on 2025-09-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0002_alter_maintenancewindows_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancewindows',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancewindows',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
