# Generated by Django 5.2.5 on 2025-11-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0002_maintenanceplans'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancewindows',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='windows_tenant', to='tenancy.tenant'),
        ),
    ]
