# Generated by Django 5.1.8 on 2026-06-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0002_remove_maintenancetasks_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceactions',
            name='maintenance_comment',
            field=models.TextField(blank=True),
        ),
    ]
