# Generated by Django 5.2.5 on 2025-11-06 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0003_maintenancewindows_day_of_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancewindows',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
