# Generated by Django 5.2.5 on 2025-10-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0003_remove_maintenancetasks_maintenance_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplans',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='plans', to='adestis_netbox_maintenance_management.maintenancetasks'),
        ),
    ]
