# Generated by Django 5.2.5 on 2025-09-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0003_alter_maintenanceplans_maintenance_action'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceactions',
            name='virtual_machine',
        ),
        migrations.AddField(
            model_name='maintenanceactions',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_actions', to='virtualization.virtualmachine'),
        ),
    ]
