# Generated by Django 5.2.5 on 2025-11-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0003_maintenancewindows_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetasks',
            name='status',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
