# Generated by Django 5.1.8 on 2025-09-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0003_alter_maintenancewindows_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancewindows',
            name='special_rule_type',
        ),
        migrations.AlterField(
            model_name='maintenancewindows',
            name='special_ordinal',
            field=models.CharField(blank=True, null=True),
        ),
    ]
