# Generated by Django 5.1.8 on 2025-09-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0004_remove_maintenancewindows_special_rule_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancewindows',
            name='url',
        ),
        migrations.RemoveField(
            model_name='maintenancewindows',
            name='version',
        ),
    ]
