# Generated by Django 5.2.5 on 2025-11-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0004_alter_maintenancewindows_day_of_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancetasks',
            options={'ordering': ('maintenance_windows__start_time',)},
        ),
        migrations.AlterField(
            model_name='maintenancewindows',
            name='recurrence_type',
            field=models.CharField(blank=True, default='select', max_length=20, null=True),
        ),
    ]
