# Generated by Django 5.2.5 on 2025-10-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0004_remove_maintenanceactions_virtual_machine_and_more'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceactions',
            name='virtual_machine',
        ),
        migrations.AddField(
            model_name='maintenanceactions',
            name='virtual_machine',
            field=models.ManyToManyField(blank=True, related_name='maintenance_actions', to='virtualization.virtualmachine'),
        ),
    ]
