# Generated by Django 5.2.5 on 2025-10-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0005_maintenanceplans_grouping_key'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplans',
            name='maintenance_windows',
            field=models.ManyToManyField(related_name='plans_maintenance_windows', to='adestis_netbox_maintenance_management.maintenancewindows'),
        ),
        migrations.AddField(
            model_name='maintenanceplans',
            name='virtual_machine',
            field=models.ManyToManyField(blank=True, related_name='plans_vm', to='virtualization.virtualmachine'),
        ),
        migrations.RemoveField(
            model_name='maintenanceplans',
            name='maintenance_action',
        ),
        migrations.AddField(
            model_name='maintenanceplans',
            name='maintenance_action',
            field=models.ManyToManyField(related_name='plans_maintenance_actions', to='adestis_netbox_maintenance_management.maintenanceactions'),
        ),
    ]
