# Generated by Django 5.2.5 on 2025-10-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0005_remove_maintenanceactions_virtual_machine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceplans',
            name='maintenance_action',
        ),
        migrations.AddField(
            model_name='maintenanceplans',
            name='maintenance_action',
            field=models.ManyToManyField(to='adestis_netbox_maintenance_management.maintenanceactions'),
        ),
    ]
