# Generated by Django 5.2.5 on 2025-11-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0005_alter_maintenancetasks_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancetasks',
            options={'ordering': ('name',)},
        ),
    ]
