# Generated by Django 5.2.5 on 2025-10-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0006_maintenanceplans_maintenance_windows_and_more'),
        ('dcim', '0210_macaddress_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetasks',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='tasks_device', to='dcim.device'),
        ),
    ]
