# Generated by Django 5.1.8 on 2025-09-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0006_maintenanceactions'),
        ('dcim', '0200_populate_mac_addresses'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceactions',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='installedapplication', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='maintenanceactions',
            name='maintenance_window',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_window', to='adestis_netbox_maintenance_management.maintenancewindows'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceactions',
            name='virtual_machine',
            field=models.ManyToManyField(blank=True, related_name='installedapplication', to='virtualization.virtualmachine'),
        ),
    ]
