# Generated by Django 5.2.5 on 2025-11-26 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0006_alter_maintenanceactions_maintenance_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceactions',
            name='maintenance_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_windows', to='adestis_netbox_maintenance_management.maintenancewindows'),
        ),
    ]
