# Generated by Django 5.1.8 on 2025-09-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0007_maintenanceactions_device_and_more'),
        ('dcim', '0200_populate_mac_addresses'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceactions',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='maintenance_actions', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='maintenanceactions',
            name='virtual_machine',
            field=models.ManyToManyField(blank=True, related_name='maintenance_actions', to='virtualization.virtualmachine'),
        ),
    ]
