# Generated by Django 5.2.5 on 2026-02-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0007_alter_maintenanceactions_maintenance_window'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceplans',
            old_name='refrence_number',
            new_name='reference_number',
        ),
    ]
