# Generated by Django 5.2.5 on 2025-11-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0008_alter_maintenancetasks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancetasks',
            options={'ordering': ('maintenance_windows__start_time', 'name')},
        ),
    ]
