# Generated by Django 5.2.5 on 2026-02-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0008_rename_refrence_number_maintenanceplans_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetasks',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
