# Generated by Django 5.2.5 on 2025-10-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0008_alter_maintenancewindows_recurrence_type_and_more'),
        ('dcim', '0210_macaddress_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplans',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='plans_device', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='maintenanceplans',
            name='maintenance_tasks',
            field=models.ManyToManyField(blank=True, related_name='plans_tasks', to='adestis_netbox_maintenance_management.maintenancetasks'),
        ),
    ]
