# Generated by Django 5.1.8 on 2025-09-03 08:25

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0008_alter_maintenanceactions_device_and_more'),
        ('extras', '0123_journalentry_kind_default'),
        ('tenancy', '0017_natural_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('maintenance_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_action', to='adestis_netbox_maintenance_management.maintenanceactions')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_tenant', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Maintenance Plans',
                'verbose_name_plural': 'Maintenance Plans',
            },
        ),
    ]
