# Generated by Django 5.2.5 on 2025-10-22 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0009_maintenanceplans_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetasks',
            name='maintenance_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_maintenance_actions', to='adestis_netbox_maintenance_management.maintenanceactions'),
        ),
    ]
