# Generated by Django 5.2.5 on 2025-11-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0009_alter_maintenancetasks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancetasks',
            options={'ordering': ('name', 'maintenance_windows__start_time')},
        ),
    ]
