# Generated by Django 5.2.5 on 2026-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0009_maintenancetasks_created_at'),
        ('dcim', '0210_macaddress_ordering'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplans',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='device_plans', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='maintenanceplans',
            name='maintenance_action',
            field=models.ManyToManyField(related_name='maintenance_action_plans', to='adestis_netbox_maintenance_management.maintenanceactions'),
        ),
        migrations.AddField(
            model_name='maintenanceplans',
            name='maintenance_windows',
            field=models.ManyToManyField(related_name='maintenance_windows_plans', to='adestis_netbox_maintenance_management.maintenancewindows'),
        ),
        migrations.AddField(
            model_name='maintenanceplans',
            name='version',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceplans',
            name='virtual_machine',
            field=models.ManyToManyField(blank=True, related_name='vm_plans', to='virtualization.virtualmachine'),
        ),
    ]
