# Generated by Django 5.2.5 on 2025-10-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0010_alter_maintenancetasks_maintenance_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancewindows',
            name='special_ordinal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
