# Generated by Django 5.1.8 on 2025-09-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0010_maintenancereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
