# Generated by Django 5.2.5 on 2026-02-19 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0010_maintenanceplans_device_and_more'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancewindows',
            name='tenant',
        ),
        migrations.AddField(
            model_name='maintenanceactions',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_tenant', to='tenancy.tenant'),
        ),
    ]
