# Generated by Django 5.2.5 on 2026-02-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0011_remove_maintenancewindows_tenant_and_more'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceplannedactions',
            options={'default_permissions': ('view',), 'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='maintenancetasks',
            name='tenant',
            field=models.ManyToManyField(blank=True, related_name='tasks_tenant', to='tenancy.tenant'),
        ),
        migrations.DeleteModel(
            name='MaintenanceReport',
        ),
    ]
