# Generated by Django 5.1.8 on 2025-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0011_maintenancereport_name'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancewindows',
            name='virtual_machine',
            field=models.ManyToManyField(blank=True, related_name='maintenance_windows', to='virtualization.virtualmachine'),
        ),
    ]
