# Generated by Django 5.2.5 on 2025-10-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0011_alter_maintenancewindows_special_ordinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancewindows',
            name='special_ordinal',
            field=models.CharField(blank=True, default='0 9 * * 1', max_length=100, null=True),
        ),
    ]
