# Generated by Django 5.1.8 on 2025-09-05 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0012_maintenancewindows_virtual_machine'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceactions',
            name='maintenance_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_windows', to='adestis_netbox_maintenance_management.maintenancewindows'),
        ),
        migrations.AlterField(
            model_name='maintenanceactions',
            name='virtual_machine',
            field=models.ManyToManyField(blank=True, related_name='maintenance_window', to='virtualization.virtualmachine'),
        ),
    ]
