# Generated by Django 5.2.5 on 2026-02-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_maintenance_management', '0012_alter_maintenanceplannedactions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceplannedactions',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='maintenancetasks',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
